### ISSUE TITLE
"Shutdown hooks" link is broken

### ISSUE THREAD

**Issue by Architector4** [spickermann/awesome-falsehoods-programmers-believe#1]
In the ["Falsehoods about Computers and Programming"](https://github.com/spickermann/awesome-falsehoods-programmers-believe#falsehoods-about-computers-and-programming) there is a "Shutdown Hooks" link that leads here: http://grimoire.ca/dev/shutdown-hooks

However, this link returns a 404.

**Comment by spickermann** [comment]
Fix the link by pointing to the latest version in the web.archive.org.

Thanks for reporting.
